INSERT INTO TRAINING(NAME, STATUS) VALUES ('Punches', 'C');
INSERT INTO TRAINING(NAME, STATUS) VALUES ('Backend - Maven intro', 'C');
INSERT INTO TRAINING(NAME, STATUS) VALUES ('Backend - Spring intro', 'A');
INSERT INTO TRAINING(NAME, STATUS) VALUES ('Backend - Testing intro', 'A');

INSERT INTO PARTICIPANT(NAME, TRAINING_ID) VALUES('Jessica Jones', 1);
INSERT INTO PARTICIPANT(NAME, TRAINING_ID) VALUES('Luke Cage', 1);
INSERT INTO PARTICIPANT(NAME, TRAINING_ID) VALUES('Coleen Wing', 2);
INSERT INTO PARTICIPANT(NAME, TRAINING_ID) VALUES('Matt Murdock', 2);
INSERT INTO PARTICIPANT(NAME, TRAINING_ID) VALUES('Danny Rand', 2);
INSERT INTO PARTICIPANT(NAME, TRAINING_ID) VALUES('Elektra', 3);
INSERT INTO PARTICIPANT(NAME, TRAINING_ID) VALUES('Cyclops', 3);
INSERT INTO PARTICIPANT(NAME, TRAINING_ID) VALUES('Storm', 4);